### ISSUE TITLE
An error occurred while installing metasploit-concern (1.0.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by Mualter** [rubygems/bundler-gem#2]
Hello everyone, as you can see on the topic I am trying to install Metasploit on ubuntu 14.04 
and i got an error while installing bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.11.1
Using thread_safe 0.3.5
Using tzinfo 0.3.44
Using activesupport 4.0.13
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.0.13
Using activemodel 4.0.13
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using activerecord 4.0.13
Using arel-helpers 2.1.0
Using bcrypt 3.1.10
Using bundler 1.10.6
Using coderay 1.1.0
Using diff-lcs 1.2.5
Using docile 1.1.5
Using factory_girl 4.5.0
Using thor 0.19.1
Using railties 4.0.13
Using factory_girl_rails 4.5.0
Using fivemat 1.2.1
Using rkelly-remix 0.0.6
Using jsobfu 0.2.1
Using json 1.8.3
Installing metasploit-concern 1.0.0

Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
An error occurred while installing metasploit-concern (1.0.0), and Bundler
cannot continue.
Make sure that `gem install metasploit-concern -v '1.0.0'` succeeds before
bundling.

what i can conclude from reading the error message is that the 'metasploit-concern 1.0.0' gem requires Ruby version >= 2.1. .
But the thing is I have ruby2.1 already
this is the output of the command rvm list:
rvm rubies

=\* ruby-2.1.0 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.1.6 [ x86_64 ]
   ruby-2.2.1 [ x86_64 ]
# => - current
# =\* - current && default
# \* - default

---

As you can see ruby-2.1.0 is already installed and set as =\* - current && default
so what is the problem ?
is ruby 2.1. different from 2.1.0 ?

any help is highly appreciated.
Thank you.

**Comment by segiddins** [comment]
Did you follow the instructions and try installing the gem directly?

**Comment by Mualter** [comment]
Yes I did and ran the command gem install metasploit-concern -v '1.0.0'
but no use.

**Comment by segiddins** [comment]
Then it's a ruby gems issue and not a bundler issue.

**Comment by Mualter** [comment]
Thank you for your time and help.
